<?php
/**
 * Handles enqueueing assets for the admin interface.
 *
 * @package OrderCategorize
 */

declare(strict_types=1);

namespace OrderCategorize\Admin\Assets;

use OrderCategorize\Admin\Page\OrderBrowserPage;
use OrderCategorize\Orders\OrderHierarchyService;
use OrderCategorize\Settings\SettingsRepository;
/**
 * Handles registering and enqueueing admin assets.
 *
 * @since 1.1.0
 */
class AdminAssets {
	/**
	 * Tracks whether the missing build notice has been registered.
	 *
	 * @var bool
	 */
	private static bool $missing_build_notice_registered = false;

	/**
	 * Register the hooks required to load assets.
	 *
	 * @since 1.1.0
	 *
	 * @return void
	 */
	public static function register(): void {
		$instance = new self();

		add_action( 'admin_enqueue_scripts', array( $instance, 'enqueue' ) );
	}

	/**
	 * Enqueue assets.
	 *
	 * @since 1.1.0
	 *
	 * @param string $hook_suffix Current admin page suffix.
	 *
	 * @return void
	 */
	public function enqueue( string $hook_suffix ): void {
		$target_hook = OrderBrowserPage::get_hook_suffix();
		if ( empty( $target_hook ) || $hook_suffix !== $target_hook ) {
			return;
		}

		$asset_path = ORCZ_BUILD_DIR . 'index.asset.php';

		if ( ! file_exists( $asset_path ) ) {
			$this->register_missing_build_notice();
			return;
		}

		/** @var array<string,mixed> $asset_file */
		$asset_file = include $asset_path;

		$this->enqueue_scripts( $asset_file );
		$this->enqueue_styles( $asset_file );

		wp_enqueue_style( 'wp-components' );

		$this->localize_script();
	}

	/**
	 * Enqueue the admin script.
	 *
	 * @since 1.1.0
	 *
	 * @param array<string,mixed> $asset_file Asset metadata generated by the build step.
	 *
	 * @return void
	 */
	private function enqueue_scripts( array $asset_file ): void {
		wp_enqueue_script(
			'orcz-admin-script',
			ORCZ_BUILD_URL . 'index.js',
			(array) ( $asset_file['dependencies'] ?? array() ),
			(string) ( $asset_file['version'] ?? ORCZ_VERSION ),
			true
		);
	}

	/**
	 * Enqueue the admin stylesheet.
	 *
	 * @since 1.1.0
	 *
	 * @param array<string,mixed> $asset_file Asset metadata generated by the build step.
	 *
	 * @return void
	 */
	private function enqueue_styles( array $asset_file ): void {
		if ( ! is_rtl() ) {
			wp_enqueue_style(
				'orcz-admin-style',
				ORCZ_BUILD_URL . 'index.css',
				array(),
				(string) ( $asset_file['version'] ?? ORCZ_VERSION )
			);

			return;
		}

		wp_enqueue_style(
			'orcz-admin-style-rtl',
			ORCZ_BUILD_URL . 'index-rtl.css',
			array(),
			(string) ( $asset_file['version'] ?? ORCZ_VERSION )
		);
	}

	/**
	 * Localize data required by the admin script.
	 *
	 * @since 1.1.0
	 *
	 * @return void
	 */
	private function localize_script(): void {
		$service      = new OrderHierarchyService();
		$initial_step = $service->get_step_data( 1, array() );

		wp_localize_script(
			'orcz-admin-script',
			'orderCategorize',
			array(
				'rootId'        => OrderBrowserPage::ROOT_NODE_ID,
				'restRoot'      => esc_url_raw( rest_url( 'order-categorize/v1' ) ),
				'nonce'         => wp_create_nonce( 'wp_rest' ),
				'settings'      => SettingsRepository::get(),
				'initialStep'   => $initial_step,
				'i18n'          => array(
					'loading'          => esc_html__( 'Loading...', 'order-categorize' ),
					'emptyStep'        => esc_html__( 'No data available for this selection.', 'order-categorize' ),
					'backLabel'        => esc_html__( 'Back', 'order-categorize' ),
					'ordersButton'     => esc_html__( 'View in WooCommerce orders', 'order-categorize' ),
					'ordersHeading'    => esc_html__( 'Matching orders', 'order-categorize' ),
					'stepHeading'      => esc_html__( 'Choose an item to drill down', 'order-categorize' ),
					'initialHeading'   => esc_html__( 'Select a product to review its orders.', 'order-categorize' ),
					'errorFetching'    => esc_html__( 'We were unable to load the data. Please try again.', 'order-categorize' ),
					'resetFilters'     => esc_html__( 'Start over', 'order-categorize' ),
					'ordersTableEmpty' => esc_html__( 'No orders match the chosen filters.', 'order-categorize' ),
					'rootLabel'        => esc_html__( 'Products', 'order-categorize' ),
					'customerLabel'    => esc_html__( 'Customer', 'order-categorize' ),
					'statusLabel'      => esc_html__( 'Status', 'order-categorize' ),
					'totalLabel'       => esc_html__( 'Total', 'order-categorize' ),
					'dateLabel'        => esc_html__( 'Date', 'order-categorize' ),
					'actionsLabel'     => esc_html__( 'Actions', 'order-categorize' ),
					'viewOrderLabel'   => esc_html__( 'View order', 'order-categorize' ),
				),
			)
		);
	}

	/**
	 * Ensure the missing asset notice is registered only once.
	 *
	 * @return void
	 */
	private function register_missing_build_notice(): void {
		if ( self::$missing_build_notice_registered ) {
			return;
		}

		self::$missing_build_notice_registered = true;

		add_action(
			'admin_notices',
			static function () {
				?>
				<div class="notice notice-warning">
					<p>
						<?php
						printf(
							/* translators: %s plugin name. */
							esc_html__( '%s assets are missing. Run the build step before using the plugin.', 'order-categorize' ),
							'<strong>' . esc_html__( 'Order Categorize', 'order-categorize' ) . '</strong>'
						);
						?>
					</p>
				</div>
				<?php
			}
		);
	}
}
