<?php
/**
 * Handles enqueueing assets for the admin interface.
 *
 * @package OrderCategorize
 */

declare(strict_types=1);

namespace OrderCategorize\Admin\Assets;

use function admin_url;
use function add_action;
use function is_rtl;
use function wp_create_nonce;
use function wp_enqueue_script;
use function wp_enqueue_style;
use function wp_localize_script;

/**
 * Handles registering and enqueueing admin assets.
 *
 * @since 1.1.0
 */
class AdminAssets {
	/**
	 * Register the hooks required to load assets.
	 *
	 * @since 1.1.0
	 *
	 * @return void
	 */
	public static function register(): void {
		$instance = new self();

		add_action( 'admin_enqueue_scripts', array( $instance, 'enqueue' ) );
	}

	/**
	 * Enqueue assets.
	 *
	 * @since 1.1.0
	 *
	 * @param string $hook_suffix Current admin page suffix.
	 *
	 * @return void
	 */
	public function enqueue( string $hook_suffix ): void {
		$asset_file = include ORCZ_BUILD_DIR . 'index.asset.php';

		$this->enqueue_scripts( $asset_file );
		$this->enqueue_styles( $asset_file );

		wp_enqueue_style( 'wp-components' );

		$this->localize_script();
	}

	/**
	 * Enqueue the admin script.
	 *
	 * @since 1.1.0
	 *
	 * @param array<string,mixed> $asset_file Asset metadata generated by the build step.
	 *
	 * @return void
	 */
	private function enqueue_scripts( array $asset_file ): void {
		wp_enqueue_script(
			'orcz-admin-script',
			ORCZ_BUILD_URL . 'index.js',
			(array) ( $asset_file['dependencies'] ?? array() ),
			(string) ( $asset_file['version'] ?? ORCZ_VERSION ),
			true
		);
	}

	/**
	 * Enqueue the admin stylesheet.
	 *
	 * @since 1.1.0
	 *
	 * @param array<string,mixed> $asset_file Asset metadata generated by the build step.
	 *
	 * @return void
	 */
	private function enqueue_styles( array $asset_file ): void {
		if ( ! is_rtl() ) {
			wp_enqueue_style(
				'orcz-admin-style',
				ORCZ_BUILD_URL . 'index.css',
				array(),
				(string) ( $asset_file['version'] ?? ORCZ_VERSION )
			);

			return;
		}

		wp_enqueue_style(
			'orcz-admin-style-rtl',
			ORCZ_BUILD_URL . 'style-index-rtl.css',
			array(),
			(string) ( $asset_file['version'] ?? ORCZ_VERSION )
		);
	}

	/**
	 * Localize data required by the admin script.
	 *
	 * @since 1.1.0
	 *
	 * @return void
	 */
	private function localize_script(): void {
	}
}
